defaultPortal: drew-dev-pract
portals:
  - name: drew-cms-for-dev-pract
    portalId: 6089181
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKOF9JrrMBILAAUAAAAAAEwAQAIY3dPzAiD94Cso7ukMMhSz8W9wqCrIzthHhIxEB6XbyfXnPzomAAAEQQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAA8AEAAAERCFFPOol7xd_ki6uPXJ5R0UE6ah-0USgNuYTFSAFoA
        expiresAt: '2023-03-05T20:01:02.628Z'
    personalAccessKey: >-
      CiQyYmNmYjM4Ny1iOWY2LTQ4MWYtODdkMi05YTU2M2RhNDBkMDgQ3dPzAhj94CsqGQAF5pGCd0B-tg0_MezaKCPLumKVXj1vwBlKA25hMQ
    sandboxAccountType: null
    parentAccountId: null
  - name: drew-dev-pract
    portalId: 20518873
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLGUwMbrMBILAA0AAAAA4E0AQAIY2a_kCSD94Cso7ukMMhSGpZO6y_hHQN9-pQQ6BPkSjrAWQjooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwD-_zE8AEAAAEQAYEIUCc7VDTARFujd27Bgpt6ey6wbuVtKA25hMVIAWgA
        expiresAt: '2023-03-06T21:24:47.282Z'
    personalAccessKey: >-
      CiQ4NzcyOTFkYi0xNDE2LTRmZjgtYmM1ZC1kOGQxMmQyMTUxZjkQ2a_kCRj94CsqGQAF5pGCoXAjdeXfnBryPAAbij3lEZYem2JKA25hMQ
