defaultPortal: drew-dev-pract
portals:
  - name: drew-cms-for-dev-pract
    portalId: 6089181
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKOF9JrrMBILAAUAAAAAAEwAQAIY3dPzAiD94Cso7ukMMhSz8W9wqCrIzthHhIxEB6XbyfXnPzomAAAEQQAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAA8AEAAAERCFFPOol7xd_ki6uPXJ5R0UE6ah-0USgNuYTFSAFoA
        expiresAt: '2023-03-05T20:01:02.628Z'
    personalAccessKey: >-
      CiQyYmNmYjM4Ny1iOWY2LTQ4MWYtODdkMi05YTU2M2RhNDBkMDgQ3dPzAhj94CsqGQAF5pGCd0B-tg0_MezaKCPLumKVXj1vwBlKA25hMQ
    sandboxAccountType: null
    parentAccountId: null
  - name: drew-dev-pract
    portalId: 20518873
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CP3C5cTsMBILAA0AAAAA4E0AQAIY2a_kCSD94Cso7ukMMhSzQQn77VsDfqBphcH7ZWSDOLA3rzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwD-_zE8AEAAAEQAYEIUE2EhqzS674-UV00hgqQG-azvOW9KA25hMVIAWgA
        expiresAt: '2023-03-09T22:59:00.607Z'
    personalAccessKey: >-
      CiQ4NzcyOTFkYi0xNDE2LTRmZjgtYmM1ZC1kOGQxMmQyMTUxZjkQ2a_kCRj94CsqGQAF5pGCoXAjdeXfnBryPAAbij3lEZYem2JKA25hMQ
